### ISSUE TITLE
After removing 'rxjs-compat' getting compilation error as "./node_modules/rxjs/add/operator/filter.js Module not found: Error: Can't resolve 'rxjs-compat/add/operator/filter'" While upgrading to angular10.

### ISSUE THREAD

**Issue by syalla157** [ranbuch/ng-broadcaster#1]
Description:

We have recently upgraded project to angular 10 and we have removed 'rxjs-compat' package because it is no longer supported in angular 10. We are using ng-broadcaster in our application and we have observed that in 'broadcaster.serivce.d.ts' imports are like this 'rxjs/add/operator/filter'. These kind of imports are not supported in rxjs 6. Please anyone check this issue.

package versions:
"rxjs": "^6.6.0",
"ng-broadcaster": "^9.1.11",
![Screenshot from 2020-07-17 18-54-40](https://user-images.githubusercontent.com/68427928/87791480-f1a82b80-c85f-11ea-84ec-f9c6f075f2b6.png)
![Screenshot from 2020-07-17 18-55-25](https://user-images.githubusercontent.com/68427928/87791518-05ec2880-c860-11ea-83d9-2e8fb505c463.png)
![ng-broadcaster](https://user-images.githubusercontent.com/68427928/87791524-084e8280-c860-11ea-9aff-90ec4e20fd1a.png)

**Comment by azherf** [comment]
Hi @ranbuch,

Can you please check this ? Even we are facing this issue.

Thanks,
Azher

**Comment by ranbuch** [comment]
@syalla157 @azherf  Apologize for the late response.
Please upgrade to version `9.10.0` and let me know if the issue has been resolved.

**Comment by azherf** [comment]
Thanks @ranbuch . It worked.
